name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyter_server
  - jupyterlite-core ==0.8.1
  - jupyterlite-xeus ==5.0.0
  - notebook ==7.6.0
  - jupyterlite-javascript-kernel ==0.3.0
  - jupyterlite-terminal==1.5.1
  - pip:
    - jupyterlite-p5-kernel==0.3.0
