name: build-env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - jupyterlab
  - jupyterlite-core==0.8.1
  - jupyterlite-xeus==5.0.0
  - notebook==7.6.0
  - pip:
    - jupyterlite-terminal==1.6.0
    - specta
    - litegitpuller
