name: xeus-kernel
channels:
  - https://prefix.dev/emscripten-forge-4x
  - https://prefix.dev/conda-forge
dependencies:
  - xeus-lua
  - xeus-sqlite
  - xeus-python
  - ipycanvas
  - numpy
  - matplotlib
  - pillow
  - ipywidgets>=8.1.6
  - ipyleaflet
  - scipy
  - plotly
  - pandas
